using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swcommands;
using SolidWorks.Interop.swconst;
using SolidWorks.Interop.cosworks;
using SolidWorks.Interop.swmotionstudy;
using System.Runtime.InteropServices;
using System.Diagnostics;

namespace SolidFormsApp1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        SldWorks swApp;
        IModelDoc2 swModel;
        AssemblyDoc swAssembly = null;
        int longstatus = 0;
        int longwarnings = 0;
        int errors = 0;

        public void ErrorMsg(object SwApp, string Message, bool EndTest)
        {
            MessageBox.Show(Message);
            MessageBox.Show("'*** WARNING - General");
            MessageBox.Show("'*** " + Message);
            MessageBox.Show("");

            if (EndTest)
            {
            }
        }

        private void ErrorMsg(string Message, bool EndTest)
        {
            swApp.SendMsgToUser2(Message, 0, 0);
            swApp.RecordLine("'*** WARNING - General");
            swApp.RecordLine("'*** " + Message);
            swApp.RecordLine("");
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            swApp = new SldWorks();
            swApp.Visible = true;
            swApp.NewPart();
            swModel = swApp.IActiveDoc2;
            
            // створення деталі
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.ClearSelection2(true);
            // створення скетчу
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0, 0, 0, -0.008500, 0, 0);
            swModel.SketchManager.CreateLine(-0.0085, 0, 0, -0.0085, 0.012000, 0);
            swModel.SketchManager.CreateLine(-0.0085, 0.012000, 0, -0.011000, 0.012000, 0);
            swModel.SketchManager.CreateLine(-0.011, 0.012, 0, -0.011, 0.023500, 0);
            swModel.SketchManager.CreateLine(-0.011, 0.023500, 0, -0.0085, 0.023500, 0);
            swModel.SketchManager.CreateLine(-0.0085, 0.0235, 0, -0.0085, 0.029000, 0);
            swModel.SketchManager.CreateLine(-0.008500, 0.029000, 0, 0, 0.029000, 0);
            swModel.SketchManager.CreateLine(0, 0.029000, 0, 0, 0, 0);
            //Обертання
            swModel.Extension.SelectByID2("Line8", "SKETCHSEGMENT", 0, 0.029, 0, true, 0, null, 0);
            swModel.ShowNamedView2("*Trimeetric", 8);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Line8", "SKETCHSEGMENT", 0, 0.029, 0, false, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, false, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.SelectionManager.EnableContourSelection = false;
            swModel.Extension.SelectByID2("", "FACE", -0.036165230813026, 1.52547209459613E-02, 1.14999999999554E-02, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, 0, 0, 0);
            //Скетч квадрату
            swModel.Extension.SelectByID2("FRONT", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.ShowNamedView2("*FRONT", 1);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0, 0, 0, -0.013500, 0, 0);
            swModel.SketchManager.CreateLine(-0.0135, -0, 0, -0.0135, -0.027000, 0);
            swModel.SketchManager.CreateLine(-0.013500, -0.027000, 0, 0.013500, -0.02700, 0);
            swModel.SketchManager.CreateLine(0.0135, -0.027, 0, 0.0135, 0, 0);
            swModel.SketchManager.CreateLine(0.0135, 0, 0, 0, 0, 0);
            swModel.ClearSelection2(true);
            //Витягування
            swModel.ClearSelection2(true);
            swModel.FeatureManager.FeatureExtrusion2(false, false, false, 0, 0, 0.0135, 0.0135, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.SelectionManager.EnableContourSelection = false;
            //Скетч бокового циліндру
            swModel.Extension.SelectByID2("FRONT", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("", "FACE", -0.036165230813026, 1.52547209459613E-02, 1.14999999999554E-02, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, 0, 0, 0);
            swModel.SketchManager.CreateLine(-0.0135, -0.0135, 0, -0.0135, -0.004, 0);
            swModel.SketchManager.CreateLine(-0.0135, -0.004, 0, -0.0215, -0.004, 0);
            swModel.SketchManager.CreateLine(-0.0215, -0.004, 0, -0.0215, -0.0135, 0);
            swModel.SketchManager.CreateLine(-0.0215, -0.0135, 0, -0.0135, -0.0135, 0);
            swModel.ClearSelection2(true);
            //Обертання_2
            swModel.Extension.SelectByID2("Line5", "SKETCHSEGMENT", -1.77589352496159E-02, -1.37331607722805E-02, 0, true, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Line5", "SKETCHSEGMENT", -1.77589352496159E-02, -1.37331607722805E-02, 0, false, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, false, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.SelectionManager.EnableContourSelection = false;
            //
            swModel.ShowNamedView2("* ", 3);
            swModel.ClearSelection2(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, -0.00655, 0, 0.000263, 0, 0);

        }

        private void Button2_Click(object sender, EventArgs e)
        {
            swApp = new SldWorks();
            swApp.Visible = true;
            swApp.NewPart();
            swModel = swApp.IActiveDoc2;

            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, -0.002313, -0.01101, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.086, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(1.58927890976202E-03, -4.2622182775176E-05, 0.085999999999899, -0.499999999999997, -0.707106781186554, -0.499999999999995, 7.06085998359418E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, 0.005995, -0.002508, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.SaveAs3("E:\\SOLID\\PARTS\\PART2.SLDPRT", 0, 2);
        }

        private void Button3_Click(object sender, EventArgs e)
        {
            swApp = new SldWorks();
            swApp.Visible = true;
            swApp.NewPart();
            swModel = swApp.IActiveDoc2;

            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, 0.008604, -0.012552, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.018, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByID2("Right Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(0, -1.52178027323264E-02, 0, -0.018, 1.52178027323264E-02, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.148, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(0.142451581747537, -4.06881931888847E-03, 0, -0.691056001762727, 8.37433943922396E-02, 0.717933594647429, 6.64233846674242E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.148, 0, 0, -0.117704, 0.000686, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.018, 0.148, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(4.63909535081079E-02, 4.67158890911592E-03, 1.79999999999723E-02, 0, 0, -1, 1.51270498009466E-03, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, -0.000325, -0.015794, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.0051, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(5.6112005093496E-03, 2.82318831773409E-03, 2.31000000000563E-02, 0.200909051120179, -0.71667734988223, -0.667839149304511, 4.6270368533032E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, -0.001105, 0.01578, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.0282, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(4.32365836530835E-04, -4.64660214501578E-03, -5.10000000008404E-03, -0.302603476714071, -0.210349118485998, 0.92961518072411, 5.46413673102162E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, -0.010965, -0.001007, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.146953850645332, -3.74549315671402E-03, 0, -0.769074800015959, -0.301483667158336, 0.56358810350927, 9.67389575452901E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.148, 0, 0, -0.139618, -0.024292, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(false, false, false, 0, 0, 0.003, 0.021, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(0.150765974910655, -8.12964857402676E-04, 2.09999999999013E-02, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.148, 0, 0, 0.167993, -0.009912, 0);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByRay(0.158886796367653, 2.33010406741982E-02, 0.017963475362194, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.158886796367653, 2.33010406741982E-02, 0.017963475362194, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 1, false, 0, 0);
            swModel.Extension.SelectByID2("", "EDGE", 0.158886796367653, 2.33010406741982E-02, 0.017963475362194, false, 1, null, 0);
            Array radiiArray2 = null;
            double[] radiis2 = new double[0];
            Array dist2Array2 = null;
            double[] dists22 = new double[0];
            Array conicRhosArray2 = null;
            double[] coniRhos2 = new double[0];
            Array setBackArray2 = null;
            double[] setBacks2 = new double[0];
            Array pointArray2 = null;
            double[] points2 = new double[0];
            Array pointDist2Array2 = null;
            double[] pointsDist22 = new double[0];
            Array pointRhoArray2 = null;
            double[] pointsRhos2 = new double[0];
            radiiArray2 = radiis2;
            dist2Array2 = dists22;
            conicRhosArray2 = coniRhos2;
            setBackArray2 = setBacks2;
            pointArray2 = points2;
            pointDist2Array2 = pointsDist22;
            pointRhoArray2 = pointsRhos2;
            swModel.FeatureManager.FeatureFillet3(195, 0.005, 0.01, 0, 0, 0, 0, radiiArray2, dist2Array2, conicRhosArray2, setBackArray2, pointArray2, pointDist2Array2, pointRhoArray2);
            swModel.Extension.SelectByRay(0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, -0.62308941573415, -0.561222253284186, 0.544783592281097, 9.59001640312899E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, -0.62308941573415, -0.561222253284186, 0.544783592281097, 9.59001640312899E-04, 1, false, 0, 0);
            swModel.Extension.SelectByID2("", "EDGE", 0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, false, 1, null, 0);
            Array radiiArray7 = null;
            double[] radiis7 = new double[0];
            Array dist2Array7 = null;
            double[] dists27 = new double[0];
            Array conicRhosArray7 = null;
            double[] coniRhos7 = new double[0];
            Array setBackArray7 = null;
            double[] setBacks7 = new double[0];
            Array pointArray7 = null;
            double[] points7 = new double[0];
            Array pointDist2Array7 = null;
            double[] pointsDist27 = new double[0];
            Array pointRhoArray7 = null;
            double[] pointsRhos7 = new double[0];
            radiiArray7 = radiis7;
            dist2Array7 = dists27;
            conicRhosArray7 = coniRhos7;
            setBackArray7 = setBacks7;
            pointArray7 = points7;
            pointDist2Array7 = pointsDist27;
            pointRhoArray7 = pointsRhos7;
            swModel.FeatureManager.FeatureFillet3(195, 0.005, 0.01, 0, 0, 0, 0, radiiArray7, dist2Array7, conicRhosArray7, setBackArray7, pointArray7, pointDist2Array7, pointRhoArray7);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateArc(0.148, 0, 0, 0.148, 0.035079, 0, 0.148, -0.035079, 0, -1);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0.148, 0.035079, 0, 0.148, -0.035079, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(false, false, false, 2, 2, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.148000000000025, 2.64179475791835E-02, 8.20256701697986E-03, -0.916442032486549, 3.40929520093096E-02, -0.398712517630453, 9.62853052522991E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.009, 0.030304, 0, -0.008645, 0.022219, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.02, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.147999999999911, -2.46182153521488E-02, 0.014226491757654, -0.432301937603105, -0.404201629892105, -0.806062080200506, 6.0976473411187E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.009, -0.030304, 0, -0.009063, -0.022612, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.02, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.128000000000156, 3.02283515616466E-02, 9.55444868782251E-03, 0.80607716063668, -6.46107070367184E-02, -0.588272953344044, 8.08835284682061E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, 0.030304, 0, 0.01258, 0.031986, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.128000000000043, -2.84411180448387E-02, 9.98263628417817E-03, 0.872881121721536, 0.154639539359259, -0.462779818281772, 9.66719932251999E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, -0.030304, 0, 0.01258, -0.031986, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.SketchManager.CreateCenterRectangle(6.69291142842794E-02, 0, 0, 1.84637429398886E-02, -0.011703285693958, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByRay(1.24055715218398E-02, 1.30801428344237E-02, 1.79999999999723E-02, 0, 0, -1, 9.36262855516639E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCenterRectangle(6.69291142842794E-02, 0, 0, 0.11539448562867, -0.011703285693958, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Sketch14", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.FeatureManager.FeatureCut4(true, false, true, 0, 0, 0.006, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByID2("Sketch15", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.FeatureManager.FeatureCut4(true, false, false, 0, 0, 0.006, 0.006, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.11539077468035, 1.17208672531746E-02, 1.45759963005503E-02, 0.816019033415538, 0.172237537755431, -0.551767312996627, 2.676397574783E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.11539077468035, 1.17208672531746E-02, 1.45759963005503E-02, 0.816019033415538, 0.172237537755431, -0.551767312996627, 2.676397574783E-04, 1, false, 0, 0);
            Array radiiArray6 = null;
            double[] radiis6 = new double[0];
            Array dist2Array6 = null;
            double[] dists26 = new double[0];
            Array conicRhosArray6 = null;
            double[] coniRhos6 = new double[0];
            Array setBackArray6 = null;
            double[] setBacks6 = new double[0];
            Array pointArray6 = null;
            double[] points6 = new double[0];
            Array pointDist2Array6 = null;
            double[] pointsDist26 = new double[0];
            Array pointRhoArray6 = null;
            double[] pointsRhos6 = new double[0];
            radiiArray6 = radiis6;
            dist2Array6 = dists26;
            conicRhosArray6 = coniRhos6;
            setBackArray6 = setBacks6;
            pointArray6 = points6;
            pointDist2Array6 = pointsDist26;
            pointRhoArray6 = pointsRhos6;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray6, dist2Array6, conicRhosArray6, setBackArray6, pointArray6, pointDist2Array6, pointRhoArray6);
            swModel.Extension.SelectByRay(0.115389812888679, -1.17058981808782E-02, 1.53856231403324E-02, 0.325648881290945, -0.582461301672596, -0.744776233621764, 6.65973361328402E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.115389812888679, -1.17058981808782E-02, 1.53856231403324E-02, 0.325648881290945, -0.582461301672596, -0.744776233621764, 6.65973361328402E-04, 1, false, 0, 0);
            Array radiiArray12 = null;
            double[] radiis12 = new double[0];
            Array dist2Array12 = null;
            double[] dists212 = new double[0];
            Array conicRhosArray12 = null;
            double[] coniRhos12 = new double[0];
            Array setBackArray12 = null;
            double[] setBacks12 = new double[0];
            Array pointArray12 = null;
            double[] points12 = new double[0];
            Array pointDist2Array12 = null;
            double[] pointsDist212 = new double[0];
            Array pointRhoArray12 = null;
            double[] pointsRhos12 = new double[0];
            radiiArray12 = radiis12;
            dist2Array12 = dists212;
            conicRhosArray12 = coniRhos12;
            setBackArray12 = setBacks12;
            pointArray12 = points12;
            pointDist2Array12 = pointsDist212;
            pointRhoArray12 = pointsRhos12;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray12, dist2Array12, conicRhosArray12, setBackArray12, pointArray12, pointDist2Array12, pointRhoArray12);
            swModel.Extension.SelectByRay(1.84319357541654E-02, -1.16653124675281E-02, 1.53420118359122E-02, -0.504463159771805, -0.422549118581304, -0.752973547224077, 6.68647953140967E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(1.84319357541654E-02, -1.16653124675281E-02, 1.53420118359122E-02, -0.504463159771805, -0.422549118581304, -0.752973547224077, 6.68647953140967E-04, 1, false, 0, 0);
            Array radiiArray17 = null;
            double[] radiis17 = new double[0];
            Array dist2Array17 = null;
            double[] dists217 = new double[0];
            Array conicRhosArray17 = null;
            double[] coniRhos17 = new double[0];
            Array setBackArray17 = null;
            double[] setBacks17 = new double[0];
            Array pointArray17 = null;
            double[] points17 = new double[0];
            Array pointDist2Array17 = null;
            double[] pointsDist217 = new double[0];
            Array pointRhoArray17 = null;
            double[] pointsRhos17 = new double[0];
            radiiArray17 = radiis17;
            dist2Array17 = dists217;
            conicRhosArray17 = coniRhos17;
            setBackArray17 = setBacks17;
            pointArray17 = points17;
            pointDist2Array17 = pointsDist217;
            pointRhoArray17 = pointsRhos17;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray17, dist2Array17, conicRhosArray17, setBackArray17, pointArray17, pointDist2Array17, pointRhoArray17);
            swModel.Extension.SelectByRay(1.85196611141691E-02, 1.17427378169737E-02, 1.46514907787605E-02, -0.350338065853215, 0.496557945684226, -0.794162103220804, 3.27668868616302E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(1.85196611141691E-02, 1.17427378169737E-02, 1.46514907787605E-02, -0.350338065853215, 0.496557945684226, -0.794162103220804, 3.27668868616302E-04, 1, false, 0, 0);
            Array radiiArray24 = null;
            double[] radiis24 = new double[0];
            Array dist2Array24 = null;
            double[] dists224 = new double[0];
            Array conicRhosArray24 = null;
            double[] coniRhos24 = new double[0];
            Array setBackArray24 = null;
            double[] setBacks24 = new double[0];
            Array pointArray24 = null;
            double[] points24 = new double[0];
            Array pointDist2Array24 = null;
            double[] pointsDist224 = new double[0];
            Array pointRhoArray24 = null;
            double[] pointsRhos24 = new double[0];
            radiiArray24 = radiis24;
            dist2Array24 = dists224;
            conicRhosArray24 = coniRhos24;
            setBackArray24 = setBacks24;
            pointArray24 = points24;
            pointDist2Array24 = pointsDist224;
            pointRhoArray24 = pointsRhos24;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray24, dist2Array24, conicRhosArray24, setBackArray24, pointArray24, pointDist2Array24, pointRhoArray24);
            swModel.Extension.SelectByRay(1.84372009059075E-02, 1.16591615853281E-02, 3.60457509492562E-03, -0.707870509720757, 0.425806291105311, 0.563567514964103, 6.47548388433103E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(1.84372009059075E-02, 1.16591615853281E-02, 3.60457509492562E-03, -0.707870509720757, 0.425806291105311, 0.563567514964103, 6.47548388433103E-04, 1, false, 0, 0);
            Array radiiArray31 = null;
            double[] radiis31 = new double[0];
            Array dist2Array31 = null;
            double[] dists231 = new double[0];
            Array conicRhosArray31 = null;
            double[] coniRhos31 = new double[0];
            Array setBackArray31 = null;
            double[] setBacks31 = new double[0];
            Array pointArray31 = null;
            double[] points31 = new double[0];
            Array pointDist2Array31 = null;
            double[] pointsDist231 = new double[0];
            Array pointRhoArray31 = null;
            double[] pointsRhos31 = new double[0];
            radiiArray31 = radiis31;
            dist2Array31 = dists231;
            conicRhosArray31 = coniRhos31;
            setBackArray31 = setBacks31;
            pointArray31 = points31;
            pointDist2Array31 = pointsDist231;
            pointRhoArray31 = pointsRhos31;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray31, dist2Array31, conicRhosArray31, setBackArray31, pointArray31, pointDist2Array31, pointRhoArray31);
            swModel.Extension.SelectByRay(1.84378813266193E-02, -1.16837204661238E-02, 3.91942760580832E-03, -0.228820043472497, -0.302457782710847, 0.92528951003612, 3.65834382143869E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(1.84378813266193E-02, -1.16837204661238E-02, 3.91942760580832E-03, -0.228820043472497, -0.302457782710847, 0.92528951003612, 3.65834382143869E-04, 1, false, 0, 0);
            Array radiiArray39 = null;
            double[] radiis39 = new double[0];
            Array dist2Array39 = null;
            double[] dists239 = new double[0];
            Array conicRhosArray39 = null;
            double[] coniRhos39 = new double[0];
            Array setBackArray39 = null;
            double[] setBacks39 = new double[0];
            Array pointArray39 = null;
            double[] points39 = new double[0];
            Array pointDist2Array39 = null;
            double[] pointsDist239 = new double[0];
            Array pointRhoArray39 = null;
            double[] pointsRhos39 = new double[0];
            radiiArray39 = radiis39;
            dist2Array39 = dists239;
            conicRhosArray39 = coniRhos39;
            setBackArray39 = setBacks39;
            pointArray39 = points39;
            pointDist2Array39 = pointsDist239;
            pointRhoArray39 = pointsRhos39;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray39, dist2Array39, conicRhosArray39, setBackArray39, pointArray39, pointDist2Array39, pointRhoArray39);
            swModel.Extension.SelectByRay(0.115523139906202, -1.16395351653296E-02, 2.01358953802355E-03, 0.406705943802946, -0.820769025820882, 0.401158923032251, 5.28917179003184E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.115523139906202, -1.16395351653296E-02, 2.01358953802355E-03, 0.406705943802946, -0.820769025820882, 0.401158923032251, 5.28917179003184E-04, 1, false, 0, 0);
            Array radiiArray48 = null;
            double[] radiis48 = new double[0];
            Array dist2Array48 = null;
            double[] dists248 = new double[0];
            Array conicRhosArray48 = null;
            double[] coniRhos48 = new double[0];
            Array setBackArray48 = null;
            double[] setBacks48 = new double[0];
            Array pointArray48 = null;
            double[] points48 = new double[0];
            Array pointDist2Array48 = null;
            double[] pointsDist248 = new double[0];
            Array pointRhoArray48 = null;
            double[] pointsRhos48 = new double[0];
            radiiArray48 = radiis48;
            dist2Array48 = dists248;
            conicRhosArray48 = coniRhos48;
            setBackArray48 = setBacks48;
            pointArray48 = points48;
            pointDist2Array48 = pointsDist248;
            pointRhoArray48 = pointsRhos48;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray48, dist2Array48, conicRhosArray48, setBackArray48, pointArray48, pointDist2Array48, pointRhoArray48);
            swModel.Extension.SelectByRay(0.115383446766543, 1.17321543136768E-02, 3.14501566043646E-03, 0.666401837366115, 0.254820565352905, 0.70069613287665, 2.21252434712161E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.115383446766543, 1.17321543136768E-02, 3.14501566043646E-03, 0.666401837366115, 0.254820565352905, 0.70069613287665, 2.21252434712161E-04, 1, false, 0, 0);
            Array radiiArray58 = null;
            double[] radiis58 = new double[0];
            Array dist2Array58 = null;
            double[] dists258 = new double[0];
            Array conicRhosArray58 = null;
            double[] coniRhos58 = new double[0];
            Array setBackArray58 = null;
            double[] setBacks58 = new double[0];
            Array pointArray58 = null;
            double[] points58 = new double[0];
            Array pointDist2Array58 = null;
            double[] pointsDist258 = new double[0];
            Array pointRhoArray58 = null;
            double[] pointsRhos58 = new double[0];
            radiiArray58 = radiis58;
            dist2Array58 = dists258;
            conicRhosArray58 = coniRhos58;
            setBackArray58 = setBacks58;
            pointArray58 = points58;
            pointDist2Array58 = pointsDist258;
            pointRhoArray58 = pointsRhos58;
            swModel.FeatureManager.FeatureFillet3(195, 0.01, 0.01, 0, 0, 0, 0, radiiArray58, dist2Array58, conicRhosArray58, setBackArray58, pointArray58, pointDist2Array58, pointRhoArray58);
            swModel.Extension.SelectByRay(0.121707379514476, 1.50433482405958E-02, 6.69471851790604E-03, 0.767247941026126, -0.38244439005289, -0.514846467899162, 4.64338856347893E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.121707379514476, 1.50433482405958E-02, 6.69471851790604E-03, 0.767247941026126, -0.38244439005289, -0.514846467899162, 4.64338856347893E-04, 1, false, 0, 0);
            Array radiiArray88 = null;
            double[] radiis88 = new double[0];
            Array dist2Array88 = null;
            double[] dists288 = new double[0];
            Array conicRhosArray88 = null;
            double[] coniRhos88 = new double[0];
            Array setBackArray88 = null;
            double[] setBacks88 = new double[0];
            Array pointArray88 = null;
            double[] points88 = new double[0];
            Array pointDist2Array88 = null;
            double[] pointsDist288 = new double[0];
            Array pointRhoArray88 = null;
            double[] pointsRhos88 = new double[0];
            radiiArray88 = radiis88;
            dist2Array88 = dists288;
            conicRhosArray88 = coniRhos88;
            setBackArray88 = setBacks88;
            pointArray88 = points88;
            pointDist2Array88 = pointsDist288;
            pointRhoArray88 = pointsRhos88;
            swModel.FeatureManager.FeatureFillet3(195, 0.1, 0.01, 0, 0, 0, 0, radiiArray88, dist2Array88, conicRhosArray88, setBackArray88, pointArray88, pointDist2Array88, pointRhoArray88);
            swModel.Extension.SelectByRay(0.121893627528209, -1.52575381688393E-02, 3.41615455391775E-03, 0.349456336895917, 0.873204510525842, 0.339697146588857, 6.8767328102871E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.121893627528209, -1.52575381688393E-02, 3.41615455391775E-03, 0.349456336895917, 0.873204510525842, 0.339697146588857, 6.8767328102871E-04, 1, false, 0, 0);
            Array radiiArray111 = null;
            double[] radiis111 = new double[0];
            Array dist2Array111 = null;
            double[] dists2111 = new double[0];
            Array conicRhosArray111 = null;
            double[] coniRhos111 = new double[0];
            Array setBackArray111 = null;
            double[] setBacks111 = new double[0];
            Array pointArray111 = null;
            double[] points111 = new double[0];
            Array pointDist2Array111 = null;
            double[] pointsDist2111 = new double[0];
            Array pointRhoArray111 = null;
            double[] pointsRhos111 = new double[0];
            radiiArray111 = radiis111;
            dist2Array111 = dists2111;
            conicRhosArray111 = coniRhos111;
            setBackArray111 = setBacks111;
            pointArray111 = points111;
            pointDist2Array111 = pointsDist2111;
            pointRhoArray111 = pointsRhos111;
            swModel.FeatureManager.FeatureFillet3(195, 0.1, 0.01, 0, 0, 0, 0, radiiArray111, dist2Array111, conicRhosArray111, setBackArray111, pointArray111, pointDist2Array111, pointRhoArray111);
            swModel.Extension.SelectByRay(0.128000000000156, 2.78240072493681E-02, 1.52475130795438E-02, 0.911154170379349, 5.59895615369895E-02, -0.408244101977257, 2.56924581309251E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, 0.030304, 0, 0.016852, 0.029352, 0);
            swModel.FeatureManager.FeatureCut4(true, false, true, 0, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByRay(0.127999999999986, -3.34315932157097E-02, 2.90706888620207E-03, 0.863711381758502, 0.494483187612594, -9.74116327206771E-02, 3.40105970886714E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, -0.030304, 0, 0.016852, -0.029352, 0);
            swModel.FeatureManager.FeatureCut4(true, false, true, 0, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            //swModel.SaveAs3("E:\\SOLID\\PARTS\\PART3.SLDPRT", 0, 2);
            swModel.Extension.SelectByID2("Top Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0, -0.0231, 0, 0, 0.0051, 0);
            swModel.SetPickMode();
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Line1@Sketch18", "EXTSKETCHSEGMENT", 0, -0.022309748988107, 0, false, 0, null, 0);
            swModel.Extension.SelectByRay(-9.63837321523897E-03, -5.32419343807078E-03, 0.018514388179085, -0.499999999999997, -0.707106781186554, -0.499999999999995, 3.44916564533835E-04, 2, true, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Line1@Sketch18", "EXTSKETCHSEGMENT", 0, -0.022309748988107, 0, false, 4, null, 0);
            swModel.Extension.SelectByRay(-9.63837321523897E-03, -5.32419343807078E-03, 0.018514388179085, -0.499999999999997, -0.707106781186554, -0.499999999999995, 3.44916564533835E-04, 2, true, 1, 0);
            swModel.InsertSplitLineProject(false, false);
            swModel.ClearSelection2(true);
            //swModel.SaveAs3("E:\\SOLID\\Simulation\\PART3S.SLDPRT", 0, 2);
        }

        private void Button4_Click(object sender, EventArgs e)
        {
            swApp = new SldWorks();
            swApp.Visible = true;
            swApp.NewPart();
            swModel = swApp.IActiveDoc2;

            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.148, 0, 0, 0.117704, 0.000686, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Arc1@Sketch1", "EXTSKETCHSEGMENT", 0.134240921858495, 2.69913946415514E-02, 0, false, 0, null, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.018, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(0.146953850645332, -3.74549315671402E-03, 0, -0.769074800015959, -0.301483667158336, 0.56358810350927, 9.67389575452901E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.148, 0, 0, -0.139618, -0.024292, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(false, false, false, 0, 0, 0.003, 0.021, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(0.150765974910655, -8.12964857402676E-04, 2.09999999999013E-02, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.148, 0, 0, 0.167993, -0.009912, 0);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByRay(0.158886796367653, 2.33010406741982E-02, 0.017963475362194, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.158886796367653, 2.33010406741982E-02, 0.017963475362194, -0.499999999999997, -0.707106781186554, -0.499999999999995, 8.12083619158696E-04, 1, false, 0, 0);
            swModel.Extension.SelectByID2("", "EDGE", 0.158886796367653, 2.33010406741982E-02, 0.017963475362194, false, 1, null, 0);
            Array radiiArray2 = null;
            double[] radiis2 = new double[0];
            Array dist2Array2 = null;
            double[] dists22 = new double[0];
            Array conicRhosArray2 = null;
            double[] coniRhos2 = new double[0];
            Array setBackArray2 = null;
            double[] setBacks2 = new double[0];
            Array pointArray2 = null;
            double[] points2 = new double[0];
            Array pointDist2Array2 = null;
            double[] pointsDist22 = new double[0];
            Array pointRhoArray2 = null;
            double[] pointsRhos2 = new double[0];
            radiiArray2 = radiis2;
            dist2Array2 = dists22;
            conicRhosArray2 = coniRhos2;
            setBackArray2 = setBacks2;
            pointArray2 = points2;
            pointDist2Array2 = pointsDist22;
            pointRhoArray2 = pointsRhos2;
            swModel.FeatureManager.FeatureFillet3(195, 0.005, 0.01, 0, 0, 0, 0, radiiArray2, dist2Array2, conicRhosArray2, setBackArray2, pointArray2, pointDist2Array2, pointRhoArray2);
            swModel.Extension.SelectByRay(0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, -0.62308941573415, -0.561222253284186, 0.544783592281097, 9.59001640312899E-04, 1, false, 0, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, -0.62308941573415, -0.561222253284186, 0.544783592281097, 9.59001640312899E-04, 1, false, 0, 0);
            swModel.Extension.SelectByID2("", "EDGE", 0.148192179134639, 2.59199361557876E-02, 2.33851184077594E-04, false, 1, null, 0);
            Array radiiArray7 = null;
            double[] radiis7 = new double[0];
            Array dist2Array7 = null;
            double[] dists27 = new double[0];
            Array conicRhosArray7 = null;
            double[] coniRhos7 = new double[0];
            Array setBackArray7 = null;
            double[] setBacks7 = new double[0];
            Array pointArray7 = null;
            double[] points7 = new double[0];
            Array pointDist2Array7 = null;
            double[] pointsDist27 = new double[0];
            Array pointRhoArray7 = null;
            double[] pointsRhos7 = new double[0];
            radiiArray7 = radiis7;
            dist2Array7 = dists27;
            conicRhosArray7 = coniRhos7;
            setBackArray7 = setBacks7;
            pointArray7 = points7;
            pointDist2Array7 = pointsDist27;
            pointRhoArray7 = pointsRhos7;
            swModel.FeatureManager.FeatureFillet3(195, 0.005, 0.01, 0, 0, 0, 0, radiiArray7, dist2Array7, conicRhosArray7, setBackArray7, pointArray7, pointDist2Array7, pointRhoArray7);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateArc(0.148, 0, 0, 0.148, 0.035079, 0, 0.148, -0.035079, 0, -1);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0.148, 0.035079, 0, 0.148, -0.035079, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(false, false, false, 2, 2, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.148000000000025, 2.64179475791835E-02, 8.20256701697986E-03, -0.916442032486549, 3.40929520093096E-02, -0.398712517630453, 9.62853052522991E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.009, 0.030304, 0, -0.008645, 0.022219, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.02, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.147999999999911, -2.46182153521488E-02, 0.014226491757654, -0.432301937603105, -0.404201629892105, -0.806062080200506, 6.0976473411187E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(-0.009, -0.030304, 0, -0.009063, -0.022612, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.02, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.128000000000156, 3.02283515616466E-02, 9.55444868782251E-03, 0.80607716063668, -6.46107070367184E-02, -0.588272953344044, 8.08835284682061E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, 0.030304, 0, 0.01258, 0.031986, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(0.128000000000043, -2.84411180448387E-02, 9.98263628417817E-03, 0.872881121721536, 0.154639539359259, -0.462779818281772, 9.66719932251999E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0.009, -0.030304, 0, 0.01258, -0.031986, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 2, 0, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            //swModel.SaveAs3("E:\\SOLID\\PARTS\\PART4.SLDPRT", 0, 2);
            //swModel.SaveAs3("E:\\SOLID\\Simulation\\PART4S.SLDPRT", 0, 2);
        }

        private void Button5_Click(object sender, EventArgs e)
        {
            swApp = new SldWorks();
            swApp.Visible = true;
            swApp.NewPart();
            swModel = swApp.IActiveDoc2;

            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(0, 0, 0, 0.046, 0.07, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Line2@Sketch1", "EXTSKETCHSEGMENT", 0, 4.63684574845615E-02, 0, true, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Line2@Sketch1", "EXTSKETCHSEGMENT", 0, 4.63684574845615E-02, 0, true, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, false, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateLine(0.046, 0, 0, 0.043, 0, 0);
            swModel.SketchManager.CreateLine(0.043, 0, 0, 0.043, 0.046, 0);
            swModel.SketchManager.CreateLine(0.043, 0.046, 0, 0.046, 0.048, 0);
            swModel.SketchManager.CreateLine(0.046, 0.048, 0, 0.046, 0, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCenterLine(0, -0.001216, 0, 0, 0.051082, 0);
            swModel.ClearSelection2(true);
            swModel.SetPickMode();
            swModel.Extension.SelectByID2("Line3", "SKETCHSEGMENT", 4.40575947375569E-02, 4.69738407554571E-02, 0, true, 0, null, 0);
            swModel.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0.045953592561034, 4.36558445643723E-02, 0, true, 0, null, 0);
            swModel.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 4.27935961885722E-02, 3.92318496429258E-02, 0, true, 0, null, 0);
            swModel.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 4.43735943748031E-02, 2.05894443022721E-04, 0, true, 0, null, 0);
            swModel.Extension.SelectByID2("Line5", "SKETCHSEGMENT", -1.82354476908064E-04, 1.72698748543164E-02, 0, true, 0, null, 0);
            swModel.SketchMirror();
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Line5", "SKETCHSEGMENT", -4.98354114154248E-04, 4.30238452898802E-02, 0.04599730039007, false, 0, null, 0);
            swModel.EditDelete();
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(false, false, false, 2, 2, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByRay(-1.28103928641614E-02, 0, 3.45280120166852E-02, 0, 1, 0, 6.80552120908572E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0, 0, 0.029, -0.029, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(true, false, false, 0, 0, 0.06, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByRay(4.30000000000064E-02, 2.81841625245249E-02, 2.13573812590084E-03, -0.75263267632674, 0.341687027100271, -0.562844587818544, 7.9593517994194E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(-1.63401346383682E-02, 0.043, 0, 1.63401346383682E-02, 0, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Sketch8", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.0049, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(-4.29999999998927E-02, 3.27430101666693E-02, -6.02078310278387E-03, 0.967565342162181, 9.17140972106926E-02, -0.235384436655037, 7.9593517994194E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(-1.63401346383682E-02, 0.043, 0, 1.63401346383682E-02, 0, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Sketch9", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.FeatureManager.FeatureExtrusion2(true, false, true, 0, 0, 0.0049, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(-0.038099999999929, 0.018935569315488, -2.78732512848023E-03, -0.675660180677068, 0.676031349199662, 0.294049205315567, 4.66182479369579E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0.0215, 0, -0.007532, 0.0088, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.024, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(3.81000000000995E-02, 1.48374661382604E-02, 2.20492750284507E-03, 0.566696222202733, 0.789383522846229, -0.236070001482671, 8.12046705245311E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0.0215, 0, -0.007532, 0.0088, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureExtrusion2(true, false, false, 0, 0, 0.024, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, true, true, true, 0, 0, false);
            swModel.Extension.SelectByRay(1.40999999999849E-02, 2.07591606829283E-02, 4.84182601127259E-03, 0.587635683347802, 0.654887984456749, -0.475190521233894, 5.66186067356448E-04, 2, false, 0, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCircle(0, 0.0215, 0, 0.0104, 0.017893, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(false, false, false, 2, 2, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SetPickMode();
            Array pointArray = null;
            double[] points = new double[9];
            points[0] = 0.043;
            points[1] = 0;
            points[2] = 0;
            points[3] = 0;
            points[4] = 0.0075;
            points[5] = 0;
            points[6] = -0.043;
            points[7] = 0;
            points[8] = 0;
            pointArray = points;
            SketchSegment skSegment = null;
            skSegment = ((SketchSegment)(swModel.SketchManager.CreateSpline(pointArray)));
            skSegment = ((SketchSegment)(swModel.SketchManager.CreateLine(-0.043000, 0.000000, 0.000000, 0.043000, 0.000000, 0.000000)));
            swModel.SetPickMode();
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.FeatureManager.FeatureCut4(false, false, false, 2, 2, 0.01, 0.01, false, false, false, false, 1.74532925199433E-02, 1.74532925199433E-02, false, false, false, false, false, true, true, true, true, false, 0, 0, false, false);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(0.046, 0.063, 0, 0.044, 0.061, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(-0.046, 0.058, 0, -0.044, 0.056, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.SketchManager.CreateCornerRectangle(0.046, 0.053, 0, 0.044, 0.051, 0);
            swModel.ClearSelection2(true);
            swModel.SketchManager.InsertSketch(true);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Right Plane", "PLANE", 0, 0, 0, true, 0, null, 0);
            swModel.InsertAxis2(true);
            swModel.Extension.SelectByID2("Sketch10", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", -4.91103805893844E-04, 4.14795942720764E-02, 0, true, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Sketch10", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", -4.91103805893844E-04, 4.14795942720764E-02, 0, true, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, true, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.Extension.SelectByID2("Sketch11", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", -1.00637826890099E-03, 3.27199284009547E-02, 0, true, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Sketch11", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", -1.00637826890099E-03, 3.27199284009547E-02, 0, true, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, true, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.Extension.SelectByID2("Sketch12", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", 5.39445120120496E-04, 3.63268496420048E-02, 0, true, 0, null, 0);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Sketch12", "SKETCH", 0, 0, 0, false, 0, null, 0);
            swModel.Extension.SelectByID2("Axis1", "AXIS", 5.39445120120496E-04, 3.63268496420048E-02, 0, true, 16, null, 0);
            swModel.FeatureManager.FeatureRevolve2(true, true, false, true, false, false, 0, 0, 6.2831853071796, 0, false, false, 0.01, 0.01, 0, 0, 0, true, true, true);
            swModel.ClearSelection2(true);
            swModel.Extension.SelectByID2("Axis1", "AXIS", 0, 0, 0, false, 0, null, 0);
            swModel.BlankRefGeom();
            swModel.Extension.SelectByRay(-0.042215774355725, 7.01627041485438E-02, 1.81347643376171E-02, 0.715628580092231, -0.3002486299042, -0.630655607757379, 6.23206710433989E-04, 1, false, 0, 0);
            swModel.FeatureManager.InsertFeatureChamfer(6, 1, 0.0015, 0.78539816339745, 0, 0, 0, 0);
            //swModel.SaveAs3("E:\\PART1.SLDPRT", 0, 2);

        }
    }
}
